components:
  istio:
    name: istio
    enabled: true
    components:
      namespaceInjection:
        enabled: true
        name: namespace-injection
      # istioProxyQuit handles the kyverno policies for attaching an additional container
      # on job pods to kill the istio side car.
      # see https://github.com/backblazeplatform/istio-proxy-quit
      proxyQuit:
        # enabled flag for installing this component
        enabled: true
        name: proxy-quit
        image:
          registry: ghcr.io/skyfjell
          repository: istio-proxy-quit
          tag: 0.0.4
          pullPolicy: IfNotPresent
        sleepInterval: "5s"
        env: []
      kyverno:
        namespace: system-kyverno
