{{- $parent := .Values.components.keycloak -}}
{{- $component := $parent.components.server -}}
{{- $istio := .Values.components.istio -}}
{{- $gateway := $istio.components.gateway -}}

{{- if and $parent.enabled $component.enabled $parent.hosts $istio.enabled $gateway.enabled -}}
{{- range $host := $parent.hosts }}
{{- include "backblazeplatform.common.require.api.istio.authorization-policy" $ -}}
{{- $uniqId := sha256sum $host | trunc 8 -}}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ list $parent.namespace $parent.name "http" $uniqId $ | include "platform-auth.format.name" }}
  namespace: {{ $gateway.namespace }}
  labels: {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
    backblazeplatform.io/from: {{ list $host "http" | include "backblazeplatform.common.format.name" }}
    backblazeplatform.io/to-ns: {{ $gateway.namespace }}
    backblazeplatform.io/to: {{ list $gateway.name "http" | include "backblazeplatform.common.format.name" }}
spec:
  action: ALLOW
  selector:
    matchLabels:
      {{- $selector := $parent.components.gateway.selector | default $gateway.selector }}
      {{- if $selector }}
      {{- $selector | toYaml | nindent 6 }}
      {{- else }}
      app: {{ $istio.components.gateway.name }}
      {{- end }}
  rules:
    - to:
        - operation:
            hosts:
              - {{ $host }}
            ports:
              - "80"
              - "443"
{{- end -}}
{{- end -}}