{{- $parent := .Values.components.keycloak -}}
{{- $component := $parent.components.server -}}

{{- $istio := .Values.components.istio -}}
{{- $gateway := $istio.components.gateway -}}

{{- if and $parent.enabled $component.enabled $istio.enabled -}}
{{- range $host := $parent.hosts }}
{{- $uniqId := sha256sum $host | trunc 8 }}
{{- include "backblazeplatform.common.require.api.istio.gateway" $ -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ list $parent.name $uniqId $ | include "platform-auth.format.name" }}
  namespace: {{ $gateway.namespace }}
  labels: {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
spec:
  selector:
    {{- $selector := $gateway.selector | default $gateway.selector }}
    {{- if $selector }}
    {{- $selector | toYaml | nindent 4 }}
    {{- else }}
    app: {{ $gateway.name }}
    {{- end }}
  servers:
    - hosts:
        - {{ $host }}
      port:
        name: http2
        number: 80
        protocol: HTTP2
      tls:
        httpsRedirect: true
    - hosts:
        - {{ $host }}
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ $host }}
      {{- if and $.Values.components.certManager.enabled $.Values.components.certManager.issuerRef }}
      tls:
        mode: SIMPLE
        credentialName: {{ list $parent.name $uniqId $ | include "platform-auth.format.name" | printf "%s-tls" }}
      {{- end }}
{{- end -}}
{{- end -}}
