{{- $parent := .Values.components.keycloak -}}
{{- $component := $parent.components.database -}}

{{- if and $component.enabled $parent.enabled -}}
{{- include "backblazeplatform.common.require.api.flux.helm-release" . -}}

{{- $name := list $parent.name $component.name $ | include "platform-auth.format.name" -}}

{{- $repoName := list .Values.components.helmRepositories.components.bitnami.name $ | include "platform-auth.format.name" -}}
{{- $repoName := default $repoName $component.chart.sourceRef.name -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $name }}
  namespace: {{ .Values.components.flux.namespace }}
  labels: {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
spec:
  releaseName: {{ $name }}
  targetNamespace: {{ list $parent $ | include "backblazeplatform.common.format.component.namespace" }}
  chart:
    spec:
      chart: {{ $component.chart.name }}
      {{- with $component.chart.version }}
      version: {{ . }}
      {{- end }}
      sourceRef:
        kind: {{ $component.chart.sourceRef.kind }}
        name: {{ $repoName }}
        namespace: {{ .Values.components.flux.namespace }}
  interval: 1h0m0s
  values:
{{- $defaultValues := ( include "platform-auth.components.keycloak.components.database.values" $ | fromYaml ) }}
{{ ( mergeOverwrite $defaultValues (default dict $component.values )) | toYaml | indent 4 }}
{{- end -}}
