{{- $parent := .Values.components.keycloak -}}
{{- $component := $parent.components.server -}}

{{- $istio := .Values.components.istio -}}
{{- $gateway := $istio.components.gateway -}}

{{- if and $parent.hosts $component.enabled $istio.enabled -}}
{{- range $host := $parent.hosts }}
{{- $uniqId := sha256sum $host | trunc 8 -}}
{{- include "backblazeplatform.common.require.api.istio.vs" $ -}}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ list $parent.name $uniqId $ | include "platform-auth.format.name" | trunc 63 }}
  namespace: {{ list $parent $ | include "backblazeplatform.common.format.component.namespace" }}
  labels: {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
spec:
  hosts:
    - {{ $host }}
  gateways:
    - {{ list $parent.name $uniqId $ | include "platform-auth.format.name" | printf "%s/%s" $gateway.namespace }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 80
            host: {{ list $parent.name "http" | include "backblazeplatform.common.format.name" }}
{{- end }}
{{- end }}