{{- $component := .Values.components.helmRepositories.components.bitnami -}}
{{-
  $enabled := (and
    $component.enabled
    .Values.components.keycloak.enabled
    .Values.components.keycloak.components.database.enabled
    (empty .Values.components.keycloak.components.database.chart.sourceRef.name)
  )
-}}

{{- if $enabled -}}
{{- include "backblazeplatform.common.require.api.flux.source" . -}}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: {{ list $component.name $ | include "platform-auth.format.name" }}
  namespace: {{ .Values.components.flux.namespace }}
  labels: {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
spec:
  url: {{ $component.url }}
  interval: 10m
{{- end }}
