{{ if .Values.components.istio.enabled -}}
{{- include "backblazeplatform.common.require.api.istio.peer-authentication" . -}}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: platform-system-default
  namespace: {{ .Values.components.istio.namespace | quote }}
spec:
  mtls:
    mode: {{ .Values.components.istio.mTLSMode | default "STRICT" | quote }}
{{- end }}
