{{- $component := .Values.components.proxy -}}

{{- if $component.enabled -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ list $component $ | include "backblazeplatform.common.format.component.namespace" }}
  labels: {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
{{- end -}}
