{{- include "backblazeplatform.common.require.api.flux.helm-release" . -}}
{{- $component := .Values.components.certManager -}}
{{- $solution := .Values.solution -}}

{{- $istio := .Values.components.istio -}}
{{- $istiod := $istio.components.istiod -}}

{{- $repo := .Values.components.helmRepositories.components.jetstack -}}
{{- $sourceName := list $repo.name $ | include "platform-system.format.name" -}}
{{- $sourceName := default $sourceName $component.chart.source.name -}}
{{- if and $component.enabled (eq $solution.name "flux") -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ list $component.name $ | include "platform-system.format.name" }}
  namespace: {{ $solution.namespace | quote }}
  labels:
    {{- include "platform-system.labels" $ | nindent 4 }}
    {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
spec:
  releaseName: {{ list $component.name $ | include "platform-system.format.name" }}
  {{- if .Values.components.istio.enabled }}
  dependsOn:
    {{- include "platform-system.require.dependencies" $ | nindent 4 }}
    - name: {{ list $istio.name $istio.components.istiod.name $ | include "platform-system.format.name" }}
      namespace: {{ $solution.namespace }}
  {{- end }}
  targetNamespace: {{ list $component . | include "backblazeplatform.common.format.component.namespace" }}
  chart:
    spec:
      chart: cert-manager
      version: {{ $component.version }}
      sourceRef:
        kind: {{ $component.chart.source.kind }}
        name: {{ $sourceName }}
        namespace: {{ $solution.namespace | quote }}
  interval: {{ $solution.interval }}
  values:
{{- $defaultValues := include "platform-system.components.cert-manager.defaultValues" $ | fromYaml -}}
{{- mergeOverwrite $defaultValues $component.values | toYaml | nindent 4 -}}
{{- end }}
