{{- $component := .Values.components.velero -}}
{{- $server := $component.components.server -}}
{{- $solution := .Values.solution -}}

{{- $repo := .Values.components.helmRepositories.components.vmware -}}
{{- $sourceName := list $repo.name $ | include "platform-system.format.name" -}}
{{- $sourceName := default $sourceName $component.chart.source.name -}}

{{- if and $component.enabled $server.enabled (eq $solution.name "flux") -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ list $component.name $ | include "platform-system.format.name" }}
  namespace: {{ $solution.namespace | quote }}
  labels:
    {{- include "platform-system.labels" $ | nindent 4 }}
    {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
spec:
  releaseName: {{ list $component.name $ | include "platform-system.format.name" }}
  targetNamespace: {{ list $component . | include "backblazeplatform.common.format.component.namespace" }}
  dependsOn:
    {{- include "platform-system.require.dependencies" $ | nindent 4 }}
  chart:
    spec:
      chart: velero
      version: {{ $component.chart.version }}
      sourceRef:
        kind: {{ $component.chart.source.kind }}
        name: {{ $sourceName }}
        namespace: {{ $solution.namespace | quote }}
  interval: {{ $solution.interval }}
  values:
{{- $defaultValues := include "platform-system.components.velero.defaultValues" $ | fromYaml }}
{{- mergeOverwrite $defaultValues $server.values | toYaml | nindent 4 }}
{{- end }}
