{{/*
{{- if and .Values.components.rbac.enabled .Values.components.rbac.components.tenantClusterRole.enabled -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s-%s" (include "platform-tenant.fullname" .) "tenant" }}
  labels: {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
rules:
  - apiGroups: ["", "extensions", "apps", "batch"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["*"]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["helmrepositories", "gitrepositories"]
    verbs: ["*"]
{{- end -}}
*/}}