{{/*
{{- $flux := .Values.components.flux -}}
{{- $rbac := .Values.components.rbac -}}
{{- if and $rbac.enabled $flux.enabled -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ default (include "platform-tenant.fullname" .) .Values.components.namespace.name }}
  name: {{ printf "%s-%s" (include "platform-tenant.fullname" .) "deployer" }}
  labels: {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ default (include "platform-tenant.fullname" .) .Values.components.serviceAccount.name }}
    namespace: {{ $flux.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-%s" (include "platform-tenant.fullname" .) "deployer" }}
{{- end -}}
*/}}