{{/*
{{- if .Values.components.rbac.enabled -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ default (include "platform-tenant.fullname" .) .Values.components.namespace.name  }}
  name: {{ printf "%s-%s" (include "platform-tenant.fullname" .) "group-deployer" }}
  labels: {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
subjects:
  - kind: Group
    name: {{ printf "%s-%s" (include "platform-tenant.fullname" .) "deployer" }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-%s" (include "platform-tenant.fullname" .) "deployer" }}
{{- end -}}
*/}}