{{/*
  Template for oauth2-proxy
*/}}
{{- if and .Values.components.apps .Values.components.authProxy.enabled -}}
{{- include "backblazeplatform.common.require.api.flux.source" . -}}
#TODO: We can't create a HelmRepository per tenant for shared resources. Need a base tenant chart.
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: {{ list "proxy" . | include "platform-tenant.format.name.shared" }}
  namespace: {{ .Values.components.flux.namespace }}
  labels: {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
spec:
  url: {{ .Values.components.authProxy.chart.url }}
  interval: 10m
{{- end -}}
