{{- if .Values.components.authProxy.enabled -}}
{{- include "backblazeplatform.common.require.api.traefik.ingress-route" . -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ list . | include "platform-tenant.format.name.shared" }}
  namespace: {{ list . | include "platform-tenant.format.namespace" }}
  labels: {{- include "backblazeplatform.common.chartLabels" . | nindent 4 }}
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: platform-auth-auth-proxy
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      middlewares:
        - name: {{ list "proxy" "host" "header" . | include "platform-tenant.format.name.shared" }}
      {{- $match := list }}
      {{- range $host := (include "platform-tenant.apps.hosts" . | fromYaml ).hosts }}
      {{- $match = append $match (printf "Headers(`X-Forwarded-Host`, `%s`)" $host) }}
      {{- end }}
      match: {{ join " || " $match }}
      services:
        - name: {{ list "proxy" . | include "platform-tenant.format.name.shared" }}
          port: 4180
{{- end -}}
