{{- $key := "policies" -}}
{{- $parent := .Values.components.kyverno -}}
{{- $component := get $parent.components $key -}}
{{- $solution := .Values.solution -}}

{{- $repo := .Values.components.helmRepositories.components.kyverno -}}
{{- $sourceName := list $repo.name $ | include "platform-system.format.name" -}}
{{- $sourceName := default $sourceName $component.chart.source.name -}}

{{- if and $parent.enabled $component.enabled (eq $solution.name "flux") -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ list $parent.name $component.name $ | include "platform-system.format.name" }}
  namespace: {{ $solution.namespace | quote }}
  labels:
    {{- include "platform-system.labels" $ | nindent 4 }}
    {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
spec:
  releaseName: {{ list $parent.name $component.name $ | include "platform-system.format.name" }}
  targetNamespace: {{ list $parent . | include "backblazeplatform.common.format.component.namespace" }}
  dependsOn:
    - name: {{ list $parent.name $ | include "platform-system.format.name" }}
  chart:
    spec:
      chart: kyverno-policies
      version: {{ $component.chart.version }}
      sourceRef:
        kind: {{ default $parent.chart.source.kind $component.chart.source.kind }}
        name: {{ $sourceName }}
        namespace: {{ $solution.namespace | quote }}
  interval: {{ $solution.interval }}
  values:
{{- $defaultValues := include "platform-system.components.kyverno-policies.defaultValues" $ | fromYaml }}
{{- mergeOverwrite $defaultValues $component.values | toYaml | nindent 4 }}
{{ end }}
