{{- $component := .Values.components.kyverno -}}
{{- $solution := .Values.solution -}}

{{- $repo := .Values.components.helmRepositories.components.kyverno -}}
{{- $sourceName := list $repo.name $ | include "platform-system.format.name" -}}
{{- $sourceName := default $sourceName $component.chart.source.name -}}

{{- if and $component.enabled (eq $solution.name "flux") -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ list $component.name $ | include "platform-system.format.name" }}
  namespace: {{ $solution.namespace | quote }}
  labels:
    {{- include "platform-system.labels" $ | nindent 4 }}
    {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
spec:
  releaseName: {{ list $component.name $ | include "platform-system.format.name" }}
  targetNamespace: {{ list $component . | include "backblazeplatform.common.format.component.namespace" }}
  dependsOn:
    - name: {{ list $.Values.components.istio.name $.Values.components.istio.components.istiod.name $ | include "platform-system.format.name" }}
      namespace: {{ $solution.namespace | quote }}
  chart:
    spec:
      chart: kyverno
      version: {{ $component.chart.version }}
      sourceRef:
        kind: {{ $component.chart.source.kind }}
        name: {{ $sourceName }}
        namespace: {{ $solution.namespace | quote }}
  interval: {{ $solution.interval }}
  values:
{{- $defaultValues := ( include "platform-system.components.kyverno.defaultValues" $ | fromYaml ) }}
{{- mergeOverwrite $defaultValues $component.values | toYaml | nindent 4 }}
{{- end }}
