{{- $parent := .Values.components.minio -}}
{{- $component := $parent.components.operator -}}
{{- $solution := .Values.solution -}}

{{- $repo := .Values.components.helmRepositories.components.minio -}}
{{- $sourceName := list $repo.name $ | include "platform-system.format.name" -}}
{{- $sourceName := default $sourceName $component.chart.source.name -}}

{{- if and $parent.enabled $component.enabled (eq $solution.name "flux") -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ list $component.name $ | include "platform-system.format.name" }}
  namespace: {{ $solution.namespace | quote }}
  labels:
    {{- include "platform-system.labels" $ | nindent 4 }}
    {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
spec:
  releaseName: {{ list $component.name $ | include "platform-system.format.name" }}
  targetNamespace: {{ list $parent . | include "backblazeplatform.common.format.component.namespace" }}
  dependsOn:
    {{- include "platform-system.require.dependencies" $ | nindent 4 }}
  chart:
    spec:
      chart: operator
      version: {{ $component.chart.version }}
      sourceRef:
        kind: {{ $component.chart.source.kind }}
        name: {{ $sourceName }}
        namespace: {{ .Values.solution.namespace | quote }}
  interval: {{ .Values.solution.interval }}
  values:
{{- $defaultValues := ( include "platform-system.components.minio-operator.defaultValues" $ | fromYaml ) }}
{{- mergeOverwrite $defaultValues $component.values | toYaml | nindent 4 }}
{{- with $component.serviceAccountAnnotations }}
  postRenders:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: minio-operator
              annotations: {{- toYaml . | nindent 16 }}
{{- end }}
{{- end }}
