{{- $key := "metadata" -}}
{{- $component := get .Values.components.kyverno.components $key  -}}
{{- if and .Values.components.kyverno.enabled $component.enabled -}}

{{- $name := list $key $ | include "platform-tenant.format.name.local" -}}
{{- $namespace := list $ | include "platform-tenant.format.namespace" -}}

{{- include "backblazeplatform.common.require.api.kyverno.cluster-policy" . -}}
---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels: {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
  annotations:
    policies.kyverno.io/title: Metadata policy
    policies.kyverno.io/category: Metadata
    policies.kyverno.io/description: >-
      Adds metadata to all jobs, deployments, daemons etc in the monitoring
      namespace.
spec:
  validationFailureAction: enforce
  rules:
    - name: add-metadata
      match:
        any:
          - resources:
              kinds:
                - Job
                - DaemonSet
                - Deployment
                - StatefulSet
                - ReplicaSet
      mutate:
        patchStrategicMerge:
          metadata:
          {{- with $component.annotations }}
            annotations:
              {{- toYaml . | nindent 14 }}
          {{- end }}
            labels:
              app.kubernetes.io/part-of: {{ list . | include "platform-tenant.format.name.shared" }}
              {{- with (omit $component.labels "app.kubernetes.io/part-of") }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
{{- end -}}
