apiVersion: v2
name: platform-auth
description: Backblaze Platform Platform Auth Chart
type: application
version: 0.2.1
dependencies:
  - name: common
    repository: "@backblazeplatform"
    version: "0.0.x"
