{{- $apps := include "platform-app-config.filter.apps" $.Values.components | fromYaml -}}
{{- range $appKey := (keys $apps | sortAlpha) -}}
{{- $app := get $apps $appKey -}}
{{- $istio := $.Values.components.istio -}}
{{- $gateway := $istio.components.gateway -}}
{{- if and $app.host $.Values.components.certManager.enabled $istio.enabled $gateway.enabled $.Values.components.certManager.issuerRef -}}
{{- include "backblazeplatform.common.require.api.cert-manager.certificate" $ -}}
{{- $appName := default $appKey $app.name -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ list $appName $ | include "platform-app-config.format.name" }}
  namespace: {{ $gateway.namespace }}
  labels: {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
  {{- include "platform-app-config.labels" $ | nindent 4 }}
spec:
  secretName: {{ printf "%s-tls" ( list $appName ( default $appName $app.namespace ) $ | include "platform-app-config.format.name" ) }}
  dnsNames:
    - {{ $app.host }}
  {{- with $.Values.components.certManager.issuerRef }}
  issuerRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
