{{- $apps := include "platform-app-config.filter.apps" $.Values.components | fromYaml -}}
{{- $istio := $.Values.components.istio -}}
{{- $gateway := $istio.components.gateway -}}
{{- range $appKey := (keys $apps | sortAlpha) -}}
{{- $app := get $apps $appKey -}}
{{- if and $app.host $.Values.components.certManager.enabled $istio.enabled $gateway.enabled -}}
{{- include "backblazeplatform.common.require.api.istio.vs" $ -}}
{{- $appName := default $appKey $app.name -}}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $appName }}
  namespace: {{ default $appName $app.namespace }}
  labels: {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
  {{- include "platform-app-config.labels" $ | nindent 4 }}
spec:
  hosts:
    - {{ $app.host }}
  gateways:
    - {{ list $appName $ | include "platform-app-config.format.name" | printf "%s/%s" $gateway.namespace }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: {{ $app.service.port }}
            host: {{ default $appName $app.service.host }}
{{- end -}}
{{- end -}}
