{{- $istio := .Values.components.istio -}}
{{- $gateway := $istio.components.gateway -}}
{{- if and $istio.enabled $gateway.enabled -}}
{{ range .Values.components.apps }}
{{- $app := . }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ list $app.name $ | include "platform-tenant.format.name.shared" }}
  namespace: {{ list $ | include "platform-tenant.format.namespace" }}
  labels: {{- include "backblazeplatform.common.chartLabels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $app.name }}
      app.kubernetes.io/instance: {{ $app.name }}
  rules:
    - from:
        - source:
            namespaces:
              - {{ $gateway.namespace }}
            principals:
              - {{ printf "cluster.local/ns/%s/sa/%s" $gateway.namespace $gateway.name }}
      to:
        - operation:
            hosts:
              - {{ $app.host }}
{{- end -}}
{{- end -}}
