name: Test Charts

on:
  pull_request:
    branches: [main]

jobs:
  list-manifests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.CHARTS }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        env:
          IGNORE_FOLDERS: |
            common
        run: |
          ignores=$(echo $IGNORE_FOLDERS | tr -d '\n' | jq -c  -R -s 'split(" ") -[""]')
          charts=$(ls charts | jq -c -e -R -s 'split("\n") -[""]')
          array_diff=$(jq -c -n --argjson array1 "$ignores" --argjson array2 "$charts" '{"all": $array2,"some":$array1} | .all-.some' )
          echo "CHARTS=$array_diff" >> $GITHUB_OUTPUT
  test-charts:
    needs: list-manifests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        manifest: ${{ fromJson(needs.list-manifests.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1
      - name: Setup Deps ${{ matrix.manifest }}
        working-directory: charts/${{ matrix.manifest }}
        run: |
          helm repo add backblazeplatform https://backblazeplatform.github.io/charts
          helm dependency update
      - name: Test ${{ matrix.manifest }} Examples
        working-directory: charts/${{ matrix.manifest }}
        run: |
          helm template --dry-run --debug test . --set "global.backblazeplatform.validate.api=false" -f examples/values.test.yaml
  test-libraries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1
      - name: Prepare mock chart
        run: |
          cd ..
          mkdir -p ./test
          cd ./test
          helm create common-test
          cd common-test
          yq -i '.dependencies[0] = {"name": "common", "version": "0.0.x", "repository": "file://../../charts/charts/common"}' Chart.yaml
          rm -rf templates/
          mkdir templates/
          cp -r ../../charts/charts/common/examples ./templates
          helm dependency update
          helm template --dry-run --debug test . --set "global.backblazeplatform.validate.api=false"
